# Generated by Django 2.0.5 on 2018-07-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180714_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course_name',
            field=models.CharField(default='computer science', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(default='Business', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
