# Generated by Django 2.0.5 on 2018-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepost',
            name='semester',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulepost',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
