# Generated by Django 2.0.5 on 2018-06-29 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180629_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulepost',
            old_name='date',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='schedulepost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
