# Generated by Django 2.0.5 on 2018-07-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180720_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepost',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='schedulepost',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='schedulepost',
            name='vote_score',
        ),
    ]
