# Generated by Django 2.0.5 on 2018-06-30 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedulepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepost',
            name='course_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulepost',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulepost',
            name='modules_taken',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='schedule_image'),
        ),
    ]
