# Generated by Django 2.0.5 on 2018-06-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20180630_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepost',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
