# Generated by Django 2.0.5 on 2018-06-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20180701_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepost',
            name='image',
        ),
    ]
