# Generated by Django 2.0.5 on 2018-06-30 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_schedulepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepost',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='schedule/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
