# Generated by Django 2.0.5 on 2018-06-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_schedulepost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepost',
            name='image',
        ),
    ]
