# Generated by Django 2.0.5 on 2018-07-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20180705_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulepost',
            old_name='id',
            new_name='schedule_id',
        ),
    ]
