# Generated by Django 2.0.5 on 2018-07-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20180705_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulepost',
            old_name='schedule_id',
            new_name='id',
        ),
    ]
