# Generated by Django 2.0.5 on 2018-07-05 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_auto_20180705_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
