# Generated by Django 2.0.5 on 2018-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20180705_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepost',
            name='faculty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
