# Generated by Django 2.0.5 on 2018-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_auto_20180705_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatepost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
